
export const AuthRoutes = {
    SplashScreen:"SplashScreen",
    WelcomeScreen:"WelcomeScreen",
    SignInScreen:"SignInScreen",
    SignUpScreen:"SignUpScreen",
    ForgotPasswordScreen:"ForgotPasswordScreen"
}


export const MainRoutes = {
    CandidatesScreen:"CandidatesScreen",
    AddCandidatesScreen:"AddCandidatesScreen",
    EditCandidatesScreen:"EditCandidatesScreen",
    HomeScreen:"HomeScreen",
    EditProfileScreen:"EditProfileScreen",
    CompanyScreen:"CompanyScreen",
    AddCompanyScreen:"AddCompanyScreen",
    ContactScreen:"ContactScreen",
    ContactDetailScreen:"ContactDetailScreen",
    AddContactScreen:"AddContactScreen",
    CandidatesDetailsScreen:"CandidatesDetailsScreen",
    JobOrderScreen:"JobOrderScreen",
    AddJobScreen:"AddJobScreen",
    JobDetailsScreen:"JobDetailsScreen",
    OnBoardingScreen:"OnBoardingScreen",
    AddonBoardingScreen:"AddonBoardingScreen",
    OnBoardingDetailsScreen:"OnBoardingDetailsScreen",
    PlacementsScreen:"PlacementsScreen",
    AddPlacementScreen:"AddPlacementScreen",
    PlacementDetailsScreen:"PlacementDetailsScreen",
    TimeSheetScreen:"TimeSheetScreen",
    AddTimesheetScreen:"AddTimesheetScreen",
    TimeSheetDetailsScreen:"TimeSheetDetailsScreen",
    ExpensesScreen:"ExpensesScreen",
    ExpensesAddScreen:"ExpensesAddScreen",
    EditCandidatesScreen:"EditCandidatesScreen",
    EditCompanyScreen:"EditCompanyScreen",
    EditContactScreen:"EditContactScreen",
    EditJobScreen:"EditJobScreen",
    EditonBoardingScreen:"EditonBoardingScreen",
    EditPlacementScreen:"EditPlacementScreen",
    EditTimesheetScreen:"EditTimesheetScreen",
    ExpensesEditScreen:"ExpensesEditScreen",
    ExpensesDetailsScreen:"ExpensesDetailsScreen",
    InvoicesScreen:"InvoicesScreen",
    DashBoardScreen:"DashBoardScreen",
    SettingsScreen:"SettingsScreen",
    CommissionReportScreen:"CommissionReportScreen",
    CompaniesActivityScreen:"CompaniesActivityScreen",
    EqualEmploymentOpportunityScreen:"EqualEmploymentOpportunityScreen",
    JobOrdersActivityScreen:"JobOrdersActivityScreen",
    PlacementDetailScreen:"PlacementDetailScreen",
    RecruiterContactSubmissionScreen:"RecruiterContactSubmissionScreen",
    RecruiterInternalSubmissionScreen:"RecruiterInternalSubmissionScreen",
    RecruitersKPIsSummaryScreen:"RecruitersKPIsSummaryScreen",
    SourcerPipelineScreen:"SourcerPipelineScreen",
    UserActivityDetailsScreen:"UserActivityDetailsScreen",
    UserActivitySummaryScreen:"UserActivitySummaryScreen",
    UserAnalyticalReportScreen:"UserAnalyticalReportScreen",
    // Setting Screee
    IntegrationsSettings:"IntegrationsSettings",
    JobBoardsSettings:"JobBoardsSettings",
    BulkEmailSettings:"BulkEmailSettings",
    CancelSubscriptionSettings:"CancelSubscriptionSettings",
    HistorySettings:"HistorySettings",
    PayForUserSubscriptioSettings:"PayForUserSubscriptioSettings",
    PayForConsultantsSettings:"PayForConsultantsSettings",
    PowerSearchCalibrationSettings:"PowerSearchCalibrationSettings",
    LeavesRequestSettings:"LeavesRequestSettings",
    WorkFlowSettings:"WorkFlowSettings",
    LocalizationSettings:"LocalizationSettings",
    FieldscustomizationSettings:"FieldscustomizationSettings",
    StatusCustomizationSettings:"StatusCustomizationSettings",
        
}